### ISSUE TITLE
Friendly Forge Format

### ISSUE THREAD

**Issue by aschrijver** [pojntfx/octarchive#1]
Hi, I just found your repo and passed along the link to the [Forge Federation](https://matrix.to/#/!SakSkZqjzMsaPCVqlv:matrix.batsense.net/$g88p2txvr9yLkgzpWEFBnNWHdo4m-CAUYgAIxZZRrmg?via=matrix.org&via=t2bot.io&via=envs.net) matrix chatroom. There is a [lot of activity](https://forgefriends.org/blog/2022/06/30/2022-06-state-forge-federation/) in the field of forge federation. And one project in this ecosystem includes the [Friendly Forge Format](https://lab.forgefriends.org/friendlyforgeformat) (F3) by [Loïc Dachary](https://mastodon.online/@dachary) (who doesn't have a Github account on principle). F3 may be interesting to your project, hence this heads-up :)

**Comment by pojntfx** [comment]
That looks very interesting! I'll take a look.

**Comment by pojntfx** [comment]
Closing this since its unlikely that I'll have the ressources to add support for this in the foreseeable future.
